# Generated by Django 3.1.1 on 2020-09-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=300)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
            options={
                'ordering': ['-created_time', '-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='NavigationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('datetime', models.DateTimeField(verbose_name='date time')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_nav_rec', to='Q1.vehicule')),
            ],
            options={
                'ordering': ['-created_time', '-last_modified'],
            },
        ),
    ]
